### ISSUE TITLE
Memory corrupted ?

### ISSUE THREAD

**Issue by sysbndt** [MahdiSafsafi/DDetours#46]
Hello,

I'm trying DDetours in one of my large applications and it fails. I nailed down the code to a very very simple test program (See attached file).

The issue is what looks like a memory corruption seen when a descriptor is removed (DDetours.pas file, TIntercept.RemoveDescriptor, lines "FreeMem(PDscr);"). This memory corruption is detected by  madExcept, turning on his option "instantly crash on buffer overrun" (Or underrun by the way).

RemoveDescriptor is called by InterceptRemove which is called in my test program from the main form destructor.  If I don't call InterceptRemove, then madExcept detect a memory leak for obvious reasons.

To check the issue with my sample program, you need to install madExcept which is free for non commercial use. Download setup at http://madshi.net/madCollection.exe. I have tested using Delphi 10.2 Tokyo but madExcept support a bunch of Delphi versions as well.

Regards
Francois Piette
Embarcadero MVP

[DetoursTest.zip](https://github.com/MahdiSafsafi/delphi-detours-library/files/1259313/DetoursTest.zip)

**Comment by MahdiSafsafi** [comment]
Hey again !
I didn't test with madExcept. DDetours uses Delphi memory manager and for descriptors, it updates memory page to the execute state. So I assume that's  why madExcept thinks that memory is corrupted. The good news, I'm already aware of this issue and for the upcoming release, it will have an embedded memory manager (this will keep code and data separated). for the bad news, this can't be fixed in current version v2 because it requires an entire changes.

> I'm trying DDetours in one of my large applications and it fails.

I'm sure you're familiar with this, but I'm going to remind you :) Be aware ! On a large project you shouldn't enable ''instantly crash on buffer overrun" on production man (for each allocated byte ... In fact you are going to allocate 1 Page (4096 byte) ! ).

Also, thanks man for your suggestions you made on my projects. They are all good ! Please feel free to share what you think !

Regards,
Mahdi.

**Comment by sysbndt** [comment]
Hi !

Thanks for your answer.

IMO madExcept really detect corruption, whatever you do. It guard each allocated block with some extra data and check that data is untouched. I'm using madExcept for years in all my applications and it always proved that any issue found was really a problem in my code. Maybe you should discuss this topic with madExcept author (Mathias Rauen, http://madshi.net). It's a really nice guy open to discussion.

My production code doesn't include madExcept of course. It is used during debugging and beta stage. Anyway I never run out of memory space. So don't worry for my code, look at yours...

Regards,
Francois Piette
Embarcadero MVP
