### ISSUE TITLE
Problem with ExtTextOutA, ExtTextOutW, DrawThemeTextEx in x86

### ISSUE THREAD

**Issue by Starina123** [MahdiSafsafi/DDetours#58]
Hi.

When I intercept ExtTextOutA, ExtTextOutW, DrawThemeTextEx functions in the 32 bit version, I am having problems.

In exe draws nothing. In dll occurs access violation.

Please tell me what could be the problem.

---
For simple test i change code of `Demo\DetoursDemo\win32api\Demo1`

```
var
  TrampolineMessageBoxW: function(hWnd: hWnd; lpText, lpCaption: LPCWSTR; uType: UINT): Integer;
stdcall = nil;

  TrampolineDrawThemeTextEx: function (hTheme: HTHEME; hdc: HDC; iPartId: Integer;
  iStateId: Integer; pszText: LPCWSTR; cchText: Integer; dwTextFlags: DWORD;
  pRect: PRect; var pOptions: TDTTOpts): HResult; stdcall = nil;


function NewDrawThemeTextEx(hTheme: HTHEME; hdc: HDC; iPartId: Integer;
  iStateId: Integer; pszText: LPCWSTR; cchText: Integer; dwTextFlags: DWORD;
  pRect: PRect; var pOptions: TDTTOpts): HResult;
begin
  pOptions.crText := ColorToRGB(clGreen);

  Result := TrampolineDrawThemeTextEx(hTheme,hdc,iPartId,
  iStateId,pszText,cchText,dwTextFlags,pRect,pOptions);
end;

procedure TMain.BtnHookClick(Sender: TObject);
begin
  if not Assigned(TrampolineMessageBoxW) then
  begin
    @TrampolineMessageBoxW := InterceptCreate(@MessageBoxW, @InterceptMessageBoxW);
  end;

  if not Assigned(TrampolineDrawThemeTextEx) then
  begin
    TrampolineDrawThemeTextEx := InterceptCreate('uxtheme.dll', 'DrawThemeTextEx', @NewDrawThemeTextEx);
  end;

  Panel1.Refresh;
end;
```

**Comment by MahdiSafsafi** [comment]
Hi, 
It draws nothings because the original function DrawThemeTextEx was not being called by the OS.
If the OS calls it or you call it explicitly then the  NewDrawThemeTextEx would be fired and draws something.
You may need to take a look at [Vcl.Styles.UxTheme](https://github.com/RRUZ/vcl-styles-utils/blob/master/Common/Vcl.Styles.UxTheme.pas) unit. it uses DDetours to hook DrawThemeTextEx , ... and works great.

For AV, please submit a minimal reproducible demo.
Thanks.

**Comment by Starina123** [comment]
I specifically checked again. The function `TrampolineDrawThemeTextEx`  is called, but nothing is drawn! Why? 

Please add the code from the description to demo project. This will show that the panel title will disappear after setting the hook.
